version: '3'

tasks:
  build:
    cmds:
      - odin build src/client -out:target/client -o:none -debug
    sources:
      - ./src/**/*.odin
      - ./deps/**/*.odin
    generates:
      - target/client
    silent: true

  build-release:
    cmds:
      - odin build src/client -out:target/client -o:speed -no-bounds-check -disable-assert -lld
    sources:
      - ./src/**/*.odin
      - ./deps/**/*.odin
    generates:
      - target/client
    silent: true

  run:
    cmds:
      - target/client
    deps:
      - build
    silent: true

  run-release:
    cmds:
      - target/client
    deps:
      - build-release
    silent: true

  test:
    cmds:
      - task: test-client
        
  test-client:
    cmds:
      - odin test src/client -out:target/client -debug
    sources:
      - ./src/client/**/*.odin
  

interval: 250ms